/*EJEMPLO USOS ALTER TABLE change, modify, rename, add*/

ALTER TABLE emp ADD c_id INTEGER;
ALTER TABLE emp MODIFY mgr NUMERIC;
ALTER TABLE emp CHANGE mgr mgr1 NUMERIC; /* El tipo NUMERIC, se verá como DECIMAL(10,0)*/
ALTER TABLE emp RENAME AS empleaditos;
ALTER TABLE empleaditos RENAME AS emp;

/*PARA CAMBIAR LA PROPIEDAD DE UNA COLUMNA, USAMOS MODIFY*/
ALTER TABLE salgrade MODIFY grade DECIMAL(10,0) NOT NULL;

ALTER TABLE salgrade ADD CONSTRAINT pk_grade PRIMARY KEY (grade); /*Convertimos el camp grade en primary Key*/

/*VAMOS A PONER UNA FOREIGN KEY QUE VAYA DESDE sal HASTA grade*/
ALTER TABLE emp ADD CONSTRAINT fk_sal_grade FOREIGN KEY(sal) REFERENCES salgrade(grade);

ALTER TABLE emp ADD THRIFPLAN NUMERIC(7,2), ADD leancode CHAR(1);

/*CREATE INDEX emp_index ON emp(ename)*/
ALTER TABLE emp ADD INDEX emp_index(ename);

/*uso de DROP TABLE*/
CREATE TABLE T11(
pk NUMERIC PRIMARY KEY,
FK NUMERIC,
C1 NUMERIC,
C2 NUMERIC);

ALTER TABLE T11 DROP PRIMARY KEY;
ALTER TABLE T11 DROP c1;
ALTER TABLE T11 DROP c2;
ALTER TABLE emp DROP INDEX emp_index;
DROP TABLE T11;
